services:
  pet_reminder_test:
    image: pet_reminder_unittest
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m unittest discover tests

  pet_reminder:
    image: pet_reminder_image
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py

  postgres_pet-reminder:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '15432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
