version: "1"

services:
  pet_reminder_test:
    image: pet_reminder_unittest
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m unittest discover tests

  pet_reminder:
    image: pet_reminder_image
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py

  postgres:
      image: postgres:14
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5438:5432'
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data